# Generated by Django 3.1.7 on 2021-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210316_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginfo',
            options={'verbose_name': 'Таблица всех зарегистрированных пользователей', 'verbose_name_plural': 'Таблица всех зарегистрированных пользователей'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'Таблица со всеми сайтами', 'verbose_name_plural': 'Таблица со всеми сайтами'},
        ),
        migrations.AlterField(
            model_name='loginfo',
            name='password',
            field=models.TextField(max_length=512, verbose_name='Пароль для авторизации'),
        ),
    ]
